#PIC
library(ggplot2);library(fields)
thin <- Tps(PP[,1:2],PP[,4])
xg <- make.surface.grid(fields.x.to.grid(PP[,1:2]))
out <- as.surface(xg, predict(thin, xg))
thin <- Tps(PP[,1:2],PP[,6])
xg <- make.surface.grid(fields.x.to.grid(PP[,1:2]))
out2 <- as.surface(xg, predict(thin, xg))

etEPS()
postscript("tps.eps", width = 10, height = 5)
par(oma=c(1,1,1,1),mar=c(2,2,2.5,1))
split.screen(c(1,2))
screen(1)
surface(out,xlab="Longitude",ylab="Latitude")
points(x=PP[,1],y=PP[,2],pch=4,cex=0.5)

screen(2)
surface(out2,xlab="Longitude",ylab="Latitude")
points(x=PP[,1],y=PP[,2],pch=4,cex=0.5)
close.screen( all=TRUE) 
dev.off()

thin <- Tps(PP[,1:2],PP[,5])
xg <- make.surface.grid(fields.x.to.grid(PP[,1:2]))
out <- as.surface(xg, predict(thin, xg))
surface(out,zlim=c(-2,5.6))
points(x=PP[,1],y=PP[,2],pch=4,cex=0.5)

data(COmonthlyMet)
str(CO.tmax[103,,])
str(CO.loc)
str(CO.ppt)